name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        run: |
          git remote add hf https://Parul06:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Parul06/TTM
          git push --force hf main:main
